// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// color_graph
List color_graph(const IntegerVector& pntr, const IntegerVector& idx, const int nvars, const bool LT);
RcppExport SEXP sparseHessianFD_color_graph(SEXP pntrSEXP, SEXP idxSEXP, SEXP nvarsSEXP, SEXP LTSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerVector& >::type pntr(pntrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< const int >::type nvars(nvarsSEXP);
    Rcpp::traits::input_parameter< const bool >::type LT(LTSEXP);
    __result = Rcpp::wrap(color_graph(pntr, idx, nvars, LT));
    return __result;
END_RCPP
}
// subst
Rcpp::S4 subst(const Rcpp::NumericMatrix& Y, const Rcpp::IntegerVector& colors, const Rcpp::ListOf<Rcpp::IntegerVector>& W, const Rcpp::IntegerVector& jCol, const Rcpp::IntegerVector& ipntr, const double& delta, const int& nvars, const int& nnz);
RcppExport SEXP sparseHessianFD_subst(SEXP YSEXP, SEXP colorsSEXP, SEXP WSEXP, SEXP jColSEXP, SEXP ipntrSEXP, SEXP deltaSEXP, SEXP nvarsSEXP, SEXP nnzSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type colors(colorsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::ListOf<Rcpp::IntegerVector>& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type jCol(jColSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ipntr(ipntrSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const int& >::type nvars(nvarsSEXP);
    Rcpp::traits::input_parameter< const int& >::type nnz(nnzSEXP);
    __result = Rcpp::wrap(subst(Y, colors, W, jCol, ipntr, delta, nvars, nnz));
    return __result;
END_RCPP
}
