# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

color <- function(rows, cols, nvars) {
    .Call('sparseHessianFD_color', PACKAGE = 'sparseHessianFD', rows, cols, nvars)
}

subst_C <- function(Y, colors, W, Sp, colsize_, delta) {
    .Call('sparseHessianFD_subst_C', PACKAGE = 'sparseHessianFD', Y, colors, W, Sp, colsize_, delta)
}

subst2 <- function(Y, colors, W, jCol_, ipntr_, delta, nvars, nnz) {
    .Call('sparseHessianFD_subst2', PACKAGE = 'sparseHessianFD', Y, colors, W, jCol_, ipntr_, delta, nvars, nnz)
}

