# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subst_C <- function(Y, colors, W, Sp, delta) {
    .Call('sparseHessianFD_subst_C', PACKAGE = 'sparseHessianFD', Y, colors, W, Sp, delta)
}

